# Generated by Django 4.0.2 on 2023-03-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mark', models.IntegerField(blank=True, null=True)),
                ('full_mark', models.IntegerField(blank=True, default=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
