# Generated by Django 4.0.2 on 2023-03-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_class'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('address', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('class_name', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main_app.class')),
            ],
        ),
    ]
