# Generated by Django 4.0.2 on 2023-03-10 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_student_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
