# Generated by Django 4.0.2 on 2023-03-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_student_roll'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('class_name', 'roll')},
        ),
    ]
